import os

from dotenv import load_dotenv

load_dotenv()

API_KEY_FORECAST_WEATHERBIT = os.getenv("API_KEY_FORECAST_WEATHERBIT")
WEATHERBIT_FORECAST_URL_HOURLY = os.getenv("WEATHERBIT_FORECAST_URL_HOURLY")
WEATHERBIT_FORECAST_URL_MINUTELY = os.getenv("WEATHERBIT_FORECAST_URL_MINUTELY")

API_KEY_FORECAST_ACCUWEATHER_HOURLY=os.getenv("API_KEY_FORECAST_ACCUWEATHER_HOURLY")
API_KEY_FORECAST_ACCUWEATHER_MINUTELY=os.getenv("API_KEY_FORECAST_ACCUWEATHER_MINUTELY")
ACCUWEATHER_FORECAST_URL_HOURLY=os.getenv("ACCUWEATHER_FORECAST_URL_HOURLY")
ACCUWEATHER_LOCATION_URL=os.getenv("ACCUWEATHER_LOCATION_URL")
ACCUWEATHER_FORECAST_URL_MINUTELY=os.getenv("ACCUWEATHER_FORECAST_URL_MINUTELY")

API_KEY_WEATHERSOURCE=os.getenv("API_KEY_WEATHERSOURCE")
WEATHERSOURCE_FORECAST_URL=os.getenv("WEATHERSOURCE_FORECAST_URL")